disabled_rules:
  - control_statement
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - private_over_fileprivate
  - type_body_length

excluded:
  - FranzCocoa/Backend.swift
  - FranzCocoaUITests/*.swift

identifier_name:
  min_length: 1

trailing_comma:
  mandatory_comma: true

type_name:
  min_length: 1
  max_length: 80

reporter: "xcode"
