disabled_rules:
  - cyclomatic_complexity
  - force_try
  - function_body_length
  - identifier_name
  - private_over_fileprivate

excluded:
  - FranzCocoa/Backend.swift

trailing_comma:
  mandatory_comma: true

reporter: "xcode"
