disabled_rules:
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - private_over_fileprivate
  - type_body_length

excluded:
  - FranzCocoa/Backend.swift

identifier_name:
  min_length: 1

trailing_comma:
  mandatory_comma: true

type_name:
  min_length: 1

reporter: "xcode"
