on: [push]
name: Test
jobs:
  test:
    runs-on: ubuntu-22.04
    name: Test Core
    services:
      kafka:
        image: confluentinc/cp-kafka:7.5.1
        ports:
          - 9092:9092
        env:
          CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
          KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:29092,PLAINTEXT_HOST://127.0.0.1:9092"
          KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
          KAFKA_CONTROLLER_QUORUM_VOTERS: "1@127.0.0.1:29093"
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
          KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
          KAFKA_JMX_HOSTNAME: "127.0.0.1"
          KAFKA_JMX_PORT: "9101"
          KAFKA_LISTENERS: "PLAINTEXT://127.0.0.1:29092,CONTROLLER://127.0.0.1:29093,PLAINTEXT_HOST://0.0.0.0:9092"
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
          KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
          KAFKA_NODE_ID: 1
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
          KAFKA_PROCESS_ROLES: "broker,controller"
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: '8.17'
      - name: Install Noise
        run: |
          env GIT_LFS_SKIP_SMUDGE=1 \
            git clone \
              --depth 1 \
              --branch racket-8.17 \
              https://github.com/Bogdanp/Noise Noise
          raco pkg install -D --batch --auto Noise/Racket/noise-serde-lib/
      - name: Prepare secrets
        run: |
          echo -n "$LICENSE_SECRET" | base64 -d > core/secrets/license-secret.txt
        env:
          LICENSE_SECRET: ${{ secrets.LICENSE_SECRET }}
      - name: Install core
        run: raco pkg install -D --batch --auto --name franz core/
      - name: Run tests
        run: |
          # HACK: Retry to get around 'coordinator not available' errors.
          raco test core/ || \
            raco test core/ || \
            raco test core/
        env:
          FRANZ_INTEGRATION_TESTS: x
